/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bed(props: any) {
  const { nodes, materials } = useGLTF('models/funitary/Bed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OBJ_Bed_Body.geometry}
        material={materials.MAT_Bed_Body}
      />
    </group>
  )
}

useGLTF.preload('models/funitary/Bed.glb')
