/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Castle(props: any) {
  const { nodes, materials } = useGLTF('/models/sims/Castle.glb') as any
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WonderWalls_SecondAge_1.geometry}
          material={materials.Stone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WonderWalls_SecondAge_2.geometry}
          material={materials.Stone_Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WonderWalls_SecondAge_3.geometry}
          material={materials.Wood}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sims/Castle.glb')
